/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StyleguideLayoutRouteImport } from './routes/styleguide/_layout'
import { Route as StyleguideLayoutIndexRouteImport } from './routes/styleguide/_layout/index'
import { Route as StyleguideLayoutTypographyRouteImport } from './routes/styleguide/_layout/typography'
import { Route as StyleguideLayoutToastRouteImport } from './routes/styleguide/_layout/toast'
import { Route as StyleguideLayoutTextareaRouteImport } from './routes/styleguide/_layout/textarea'
import { Route as StyleguideLayoutTabsRouteImport } from './routes/styleguide/_layout/tabs'
import { Route as StyleguideLayoutTableRouteImport } from './routes/styleguide/_layout/table'
import { Route as StyleguideLayoutSpacingRouteImport } from './routes/styleguide/_layout/spacing'
import { Route as StyleguideLayoutSkeletonRouteImport } from './routes/styleguide/_layout/skeleton'
import { Route as StyleguideLayoutSidebarRouteImport } from './routes/styleguide/_layout/sidebar'
import { Route as StyleguideLayoutSheetRouteImport } from './routes/styleguide/_layout/sheet'
import { Route as StyleguideLayoutShadowsRouteImport } from './routes/styleguide/_layout/shadows'
import { Route as StyleguideLayoutSeparatorRouteImport } from './routes/styleguide/_layout/separator'
import { Route as StyleguideLayoutSelectRouteImport } from './routes/styleguide/_layout/select'
import { Route as StyleguideLayoutPopoverRouteImport } from './routes/styleguide/_layout/popover'
import { Route as StyleguideLayoutInputRouteImport } from './routes/styleguide/_layout/input'
import { Route as StyleguideLayoutFormsRouteImport } from './routes/styleguide/_layout/forms'
import { Route as StyleguideLayoutDropdownMenuRouteImport } from './routes/styleguide/_layout/dropdown-menu'
import { Route as StyleguideLayoutDialogRouteImport } from './routes/styleguide/_layout/dialog'
import { Route as StyleguideLayoutDatePickerRouteImport } from './routes/styleguide/_layout/date-picker'
import { Route as StyleguideLayoutCommandRouteImport } from './routes/styleguide/_layout/command'
import { Route as StyleguideLayoutColorsRouteImport } from './routes/styleguide/_layout/colors'
import { Route as StyleguideLayoutCardsRouteImport } from './routes/styleguide/_layout/cards'
import { Route as StyleguideLayoutCalendarRouteImport } from './routes/styleguide/_layout/calendar'
import { Route as StyleguideLayoutButtonsRouteImport } from './routes/styleguide/_layout/buttons'
import { Route as StyleguideLayoutBreadcrumbRouteImport } from './routes/styleguide/_layout/breadcrumb'
import { Route as StyleguideLayoutBadgesRouteImport } from './routes/styleguide/_layout/badges'
import { Route as StyleguideLayoutAvatarRouteImport } from './routes/styleguide/_layout/avatar'
import { Route as StyleguideLayoutAlertsRouteImport } from './routes/styleguide/_layout/alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideLayoutRoute = StyleguideLayoutRouteImport.update({
  id: '/styleguide/_layout',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideLayoutIndexRoute = StyleguideLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutTypographyRoute =
  StyleguideLayoutTypographyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutToastRoute = StyleguideLayoutToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutTextareaRoute =
  StyleguideLayoutTextareaRouteImport.update({
    id: '/textarea',
    path: '/textarea',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutTabsRoute = StyleguideLayoutTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutTableRoute = StyleguideLayoutTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutSpacingRoute = StyleguideLayoutSpacingRouteImport.update({
  id: '/spacing',
  path: '/spacing',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutSkeletonRoute =
  StyleguideLayoutSkeletonRouteImport.update({
    id: '/skeleton',
    path: '/skeleton',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutSidebarRoute = StyleguideLayoutSidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutSheetRoute = StyleguideLayoutSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutShadowsRoute = StyleguideLayoutShadowsRouteImport.update({
  id: '/shadows',
  path: '/shadows',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutSeparatorRoute =
  StyleguideLayoutSeparatorRouteImport.update({
    id: '/separator',
    path: '/separator',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutSelectRoute = StyleguideLayoutSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutPopoverRoute = StyleguideLayoutPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutInputRoute = StyleguideLayoutInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutFormsRoute = StyleguideLayoutFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutDropdownMenuRoute =
  StyleguideLayoutDropdownMenuRouteImport.update({
    id: '/dropdown-menu',
    path: '/dropdown-menu',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutDialogRoute = StyleguideLayoutDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutDatePickerRoute =
  StyleguideLayoutDatePickerRouteImport.update({
    id: '/date-picker',
    path: '/date-picker',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutCommandRoute = StyleguideLayoutCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutColorsRoute = StyleguideLayoutColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutCardsRoute = StyleguideLayoutCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutCalendarRoute =
  StyleguideLayoutCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutButtonsRoute = StyleguideLayoutButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutBreadcrumbRoute =
  StyleguideLayoutBreadcrumbRouteImport.update({
    id: '/breadcrumb',
    path: '/breadcrumb',
    getParentRoute: () => StyleguideLayoutRoute,
  } as any)
const StyleguideLayoutBadgesRoute = StyleguideLayoutBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutAvatarRoute = StyleguideLayoutAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)
const StyleguideLayoutAlertsRoute = StyleguideLayoutAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => StyleguideLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/styleguide': typeof StyleguideLayoutRouteWithChildren
  '/styleguide/alerts': typeof StyleguideLayoutAlertsRoute
  '/styleguide/avatar': typeof StyleguideLayoutAvatarRoute
  '/styleguide/badges': typeof StyleguideLayoutBadgesRoute
  '/styleguide/breadcrumb': typeof StyleguideLayoutBreadcrumbRoute
  '/styleguide/buttons': typeof StyleguideLayoutButtonsRoute
  '/styleguide/calendar': typeof StyleguideLayoutCalendarRoute
  '/styleguide/cards': typeof StyleguideLayoutCardsRoute
  '/styleguide/colors': typeof StyleguideLayoutColorsRoute
  '/styleguide/command': typeof StyleguideLayoutCommandRoute
  '/styleguide/date-picker': typeof StyleguideLayoutDatePickerRoute
  '/styleguide/dialog': typeof StyleguideLayoutDialogRoute
  '/styleguide/dropdown-menu': typeof StyleguideLayoutDropdownMenuRoute
  '/styleguide/forms': typeof StyleguideLayoutFormsRoute
  '/styleguide/input': typeof StyleguideLayoutInputRoute
  '/styleguide/popover': typeof StyleguideLayoutPopoverRoute
  '/styleguide/select': typeof StyleguideLayoutSelectRoute
  '/styleguide/separator': typeof StyleguideLayoutSeparatorRoute
  '/styleguide/shadows': typeof StyleguideLayoutShadowsRoute
  '/styleguide/sheet': typeof StyleguideLayoutSheetRoute
  '/styleguide/sidebar': typeof StyleguideLayoutSidebarRoute
  '/styleguide/skeleton': typeof StyleguideLayoutSkeletonRoute
  '/styleguide/spacing': typeof StyleguideLayoutSpacingRoute
  '/styleguide/table': typeof StyleguideLayoutTableRoute
  '/styleguide/tabs': typeof StyleguideLayoutTabsRoute
  '/styleguide/textarea': typeof StyleguideLayoutTextareaRoute
  '/styleguide/toast': typeof StyleguideLayoutToastRoute
  '/styleguide/typography': typeof StyleguideLayoutTypographyRoute
  '/styleguide/': typeof StyleguideLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/styleguide/alerts': typeof StyleguideLayoutAlertsRoute
  '/styleguide/avatar': typeof StyleguideLayoutAvatarRoute
  '/styleguide/badges': typeof StyleguideLayoutBadgesRoute
  '/styleguide/breadcrumb': typeof StyleguideLayoutBreadcrumbRoute
  '/styleguide/buttons': typeof StyleguideLayoutButtonsRoute
  '/styleguide/calendar': typeof StyleguideLayoutCalendarRoute
  '/styleguide/cards': typeof StyleguideLayoutCardsRoute
  '/styleguide/colors': typeof StyleguideLayoutColorsRoute
  '/styleguide/command': typeof StyleguideLayoutCommandRoute
  '/styleguide/date-picker': typeof StyleguideLayoutDatePickerRoute
  '/styleguide/dialog': typeof StyleguideLayoutDialogRoute
  '/styleguide/dropdown-menu': typeof StyleguideLayoutDropdownMenuRoute
  '/styleguide/forms': typeof StyleguideLayoutFormsRoute
  '/styleguide/input': typeof StyleguideLayoutInputRoute
  '/styleguide/popover': typeof StyleguideLayoutPopoverRoute
  '/styleguide/select': typeof StyleguideLayoutSelectRoute
  '/styleguide/separator': typeof StyleguideLayoutSeparatorRoute
  '/styleguide/shadows': typeof StyleguideLayoutShadowsRoute
  '/styleguide/sheet': typeof StyleguideLayoutSheetRoute
  '/styleguide/sidebar': typeof StyleguideLayoutSidebarRoute
  '/styleguide/skeleton': typeof StyleguideLayoutSkeletonRoute
  '/styleguide/spacing': typeof StyleguideLayoutSpacingRoute
  '/styleguide/table': typeof StyleguideLayoutTableRoute
  '/styleguide/tabs': typeof StyleguideLayoutTabsRoute
  '/styleguide/textarea': typeof StyleguideLayoutTextareaRoute
  '/styleguide/toast': typeof StyleguideLayoutToastRoute
  '/styleguide/typography': typeof StyleguideLayoutTypographyRoute
  '/styleguide': typeof StyleguideLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/styleguide/_layout': typeof StyleguideLayoutRouteWithChildren
  '/styleguide/_layout/alerts': typeof StyleguideLayoutAlertsRoute
  '/styleguide/_layout/avatar': typeof StyleguideLayoutAvatarRoute
  '/styleguide/_layout/badges': typeof StyleguideLayoutBadgesRoute
  '/styleguide/_layout/breadcrumb': typeof StyleguideLayoutBreadcrumbRoute
  '/styleguide/_layout/buttons': typeof StyleguideLayoutButtonsRoute
  '/styleguide/_layout/calendar': typeof StyleguideLayoutCalendarRoute
  '/styleguide/_layout/cards': typeof StyleguideLayoutCardsRoute
  '/styleguide/_layout/colors': typeof StyleguideLayoutColorsRoute
  '/styleguide/_layout/command': typeof StyleguideLayoutCommandRoute
  '/styleguide/_layout/date-picker': typeof StyleguideLayoutDatePickerRoute
  '/styleguide/_layout/dialog': typeof StyleguideLayoutDialogRoute
  '/styleguide/_layout/dropdown-menu': typeof StyleguideLayoutDropdownMenuRoute
  '/styleguide/_layout/forms': typeof StyleguideLayoutFormsRoute
  '/styleguide/_layout/input': typeof StyleguideLayoutInputRoute
  '/styleguide/_layout/popover': typeof StyleguideLayoutPopoverRoute
  '/styleguide/_layout/select': typeof StyleguideLayoutSelectRoute
  '/styleguide/_layout/separator': typeof StyleguideLayoutSeparatorRoute
  '/styleguide/_layout/shadows': typeof StyleguideLayoutShadowsRoute
  '/styleguide/_layout/sheet': typeof StyleguideLayoutSheetRoute
  '/styleguide/_layout/sidebar': typeof StyleguideLayoutSidebarRoute
  '/styleguide/_layout/skeleton': typeof StyleguideLayoutSkeletonRoute
  '/styleguide/_layout/spacing': typeof StyleguideLayoutSpacingRoute
  '/styleguide/_layout/table': typeof StyleguideLayoutTableRoute
  '/styleguide/_layout/tabs': typeof StyleguideLayoutTabsRoute
  '/styleguide/_layout/textarea': typeof StyleguideLayoutTextareaRoute
  '/styleguide/_layout/toast': typeof StyleguideLayoutToastRoute
  '/styleguide/_layout/typography': typeof StyleguideLayoutTypographyRoute
  '/styleguide/_layout/': typeof StyleguideLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/styleguide'
    | '/styleguide/alerts'
    | '/styleguide/avatar'
    | '/styleguide/badges'
    | '/styleguide/breadcrumb'
    | '/styleguide/buttons'
    | '/styleguide/calendar'
    | '/styleguide/cards'
    | '/styleguide/colors'
    | '/styleguide/command'
    | '/styleguide/date-picker'
    | '/styleguide/dialog'
    | '/styleguide/dropdown-menu'
    | '/styleguide/forms'
    | '/styleguide/input'
    | '/styleguide/popover'
    | '/styleguide/select'
    | '/styleguide/separator'
    | '/styleguide/shadows'
    | '/styleguide/sheet'
    | '/styleguide/sidebar'
    | '/styleguide/skeleton'
    | '/styleguide/spacing'
    | '/styleguide/table'
    | '/styleguide/tabs'
    | '/styleguide/textarea'
    | '/styleguide/toast'
    | '/styleguide/typography'
    | '/styleguide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/styleguide/alerts'
    | '/styleguide/avatar'
    | '/styleguide/badges'
    | '/styleguide/breadcrumb'
    | '/styleguide/buttons'
    | '/styleguide/calendar'
    | '/styleguide/cards'
    | '/styleguide/colors'
    | '/styleguide/command'
    | '/styleguide/date-picker'
    | '/styleguide/dialog'
    | '/styleguide/dropdown-menu'
    | '/styleguide/forms'
    | '/styleguide/input'
    | '/styleguide/popover'
    | '/styleguide/select'
    | '/styleguide/separator'
    | '/styleguide/shadows'
    | '/styleguide/sheet'
    | '/styleguide/sidebar'
    | '/styleguide/skeleton'
    | '/styleguide/spacing'
    | '/styleguide/table'
    | '/styleguide/tabs'
    | '/styleguide/textarea'
    | '/styleguide/toast'
    | '/styleguide/typography'
    | '/styleguide'
  id:
    | '__root__'
    | '/'
    | '/styleguide/_layout'
    | '/styleguide/_layout/alerts'
    | '/styleguide/_layout/avatar'
    | '/styleguide/_layout/badges'
    | '/styleguide/_layout/breadcrumb'
    | '/styleguide/_layout/buttons'
    | '/styleguide/_layout/calendar'
    | '/styleguide/_layout/cards'
    | '/styleguide/_layout/colors'
    | '/styleguide/_layout/command'
    | '/styleguide/_layout/date-picker'
    | '/styleguide/_layout/dialog'
    | '/styleguide/_layout/dropdown-menu'
    | '/styleguide/_layout/forms'
    | '/styleguide/_layout/input'
    | '/styleguide/_layout/popover'
    | '/styleguide/_layout/select'
    | '/styleguide/_layout/separator'
    | '/styleguide/_layout/shadows'
    | '/styleguide/_layout/sheet'
    | '/styleguide/_layout/sidebar'
    | '/styleguide/_layout/skeleton'
    | '/styleguide/_layout/spacing'
    | '/styleguide/_layout/table'
    | '/styleguide/_layout/tabs'
    | '/styleguide/_layout/textarea'
    | '/styleguide/_layout/toast'
    | '/styleguide/_layout/typography'
    | '/styleguide/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StyleguideLayoutRoute: typeof StyleguideLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide/_layout': {
      id: '/styleguide/_layout'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide/_layout/': {
      id: '/styleguide/_layout/'
      path: '/'
      fullPath: '/styleguide/'
      preLoaderRoute: typeof StyleguideLayoutIndexRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/typography': {
      id: '/styleguide/_layout/typography'
      path: '/typography'
      fullPath: '/styleguide/typography'
      preLoaderRoute: typeof StyleguideLayoutTypographyRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/toast': {
      id: '/styleguide/_layout/toast'
      path: '/toast'
      fullPath: '/styleguide/toast'
      preLoaderRoute: typeof StyleguideLayoutToastRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/textarea': {
      id: '/styleguide/_layout/textarea'
      path: '/textarea'
      fullPath: '/styleguide/textarea'
      preLoaderRoute: typeof StyleguideLayoutTextareaRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/tabs': {
      id: '/styleguide/_layout/tabs'
      path: '/tabs'
      fullPath: '/styleguide/tabs'
      preLoaderRoute: typeof StyleguideLayoutTabsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/table': {
      id: '/styleguide/_layout/table'
      path: '/table'
      fullPath: '/styleguide/table'
      preLoaderRoute: typeof StyleguideLayoutTableRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/spacing': {
      id: '/styleguide/_layout/spacing'
      path: '/spacing'
      fullPath: '/styleguide/spacing'
      preLoaderRoute: typeof StyleguideLayoutSpacingRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/skeleton': {
      id: '/styleguide/_layout/skeleton'
      path: '/skeleton'
      fullPath: '/styleguide/skeleton'
      preLoaderRoute: typeof StyleguideLayoutSkeletonRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/sidebar': {
      id: '/styleguide/_layout/sidebar'
      path: '/sidebar'
      fullPath: '/styleguide/sidebar'
      preLoaderRoute: typeof StyleguideLayoutSidebarRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/sheet': {
      id: '/styleguide/_layout/sheet'
      path: '/sheet'
      fullPath: '/styleguide/sheet'
      preLoaderRoute: typeof StyleguideLayoutSheetRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/shadows': {
      id: '/styleguide/_layout/shadows'
      path: '/shadows'
      fullPath: '/styleguide/shadows'
      preLoaderRoute: typeof StyleguideLayoutShadowsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/separator': {
      id: '/styleguide/_layout/separator'
      path: '/separator'
      fullPath: '/styleguide/separator'
      preLoaderRoute: typeof StyleguideLayoutSeparatorRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/select': {
      id: '/styleguide/_layout/select'
      path: '/select'
      fullPath: '/styleguide/select'
      preLoaderRoute: typeof StyleguideLayoutSelectRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/popover': {
      id: '/styleguide/_layout/popover'
      path: '/popover'
      fullPath: '/styleguide/popover'
      preLoaderRoute: typeof StyleguideLayoutPopoverRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/input': {
      id: '/styleguide/_layout/input'
      path: '/input'
      fullPath: '/styleguide/input'
      preLoaderRoute: typeof StyleguideLayoutInputRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/forms': {
      id: '/styleguide/_layout/forms'
      path: '/forms'
      fullPath: '/styleguide/forms'
      preLoaderRoute: typeof StyleguideLayoutFormsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/dropdown-menu': {
      id: '/styleguide/_layout/dropdown-menu'
      path: '/dropdown-menu'
      fullPath: '/styleguide/dropdown-menu'
      preLoaderRoute: typeof StyleguideLayoutDropdownMenuRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/dialog': {
      id: '/styleguide/_layout/dialog'
      path: '/dialog'
      fullPath: '/styleguide/dialog'
      preLoaderRoute: typeof StyleguideLayoutDialogRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/date-picker': {
      id: '/styleguide/_layout/date-picker'
      path: '/date-picker'
      fullPath: '/styleguide/date-picker'
      preLoaderRoute: typeof StyleguideLayoutDatePickerRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/command': {
      id: '/styleguide/_layout/command'
      path: '/command'
      fullPath: '/styleguide/command'
      preLoaderRoute: typeof StyleguideLayoutCommandRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/colors': {
      id: '/styleguide/_layout/colors'
      path: '/colors'
      fullPath: '/styleguide/colors'
      preLoaderRoute: typeof StyleguideLayoutColorsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/cards': {
      id: '/styleguide/_layout/cards'
      path: '/cards'
      fullPath: '/styleguide/cards'
      preLoaderRoute: typeof StyleguideLayoutCardsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/calendar': {
      id: '/styleguide/_layout/calendar'
      path: '/calendar'
      fullPath: '/styleguide/calendar'
      preLoaderRoute: typeof StyleguideLayoutCalendarRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/buttons': {
      id: '/styleguide/_layout/buttons'
      path: '/buttons'
      fullPath: '/styleguide/buttons'
      preLoaderRoute: typeof StyleguideLayoutButtonsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/breadcrumb': {
      id: '/styleguide/_layout/breadcrumb'
      path: '/breadcrumb'
      fullPath: '/styleguide/breadcrumb'
      preLoaderRoute: typeof StyleguideLayoutBreadcrumbRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/badges': {
      id: '/styleguide/_layout/badges'
      path: '/badges'
      fullPath: '/styleguide/badges'
      preLoaderRoute: typeof StyleguideLayoutBadgesRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/avatar': {
      id: '/styleguide/_layout/avatar'
      path: '/avatar'
      fullPath: '/styleguide/avatar'
      preLoaderRoute: typeof StyleguideLayoutAvatarRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
    '/styleguide/_layout/alerts': {
      id: '/styleguide/_layout/alerts'
      path: '/alerts'
      fullPath: '/styleguide/alerts'
      preLoaderRoute: typeof StyleguideLayoutAlertsRouteImport
      parentRoute: typeof StyleguideLayoutRoute
    }
  }
}

interface StyleguideLayoutRouteChildren {
  StyleguideLayoutAlertsRoute: typeof StyleguideLayoutAlertsRoute
  StyleguideLayoutAvatarRoute: typeof StyleguideLayoutAvatarRoute
  StyleguideLayoutBadgesRoute: typeof StyleguideLayoutBadgesRoute
  StyleguideLayoutBreadcrumbRoute: typeof StyleguideLayoutBreadcrumbRoute
  StyleguideLayoutButtonsRoute: typeof StyleguideLayoutButtonsRoute
  StyleguideLayoutCalendarRoute: typeof StyleguideLayoutCalendarRoute
  StyleguideLayoutCardsRoute: typeof StyleguideLayoutCardsRoute
  StyleguideLayoutColorsRoute: typeof StyleguideLayoutColorsRoute
  StyleguideLayoutCommandRoute: typeof StyleguideLayoutCommandRoute
  StyleguideLayoutDatePickerRoute: typeof StyleguideLayoutDatePickerRoute
  StyleguideLayoutDialogRoute: typeof StyleguideLayoutDialogRoute
  StyleguideLayoutDropdownMenuRoute: typeof StyleguideLayoutDropdownMenuRoute
  StyleguideLayoutFormsRoute: typeof StyleguideLayoutFormsRoute
  StyleguideLayoutInputRoute: typeof StyleguideLayoutInputRoute
  StyleguideLayoutPopoverRoute: typeof StyleguideLayoutPopoverRoute
  StyleguideLayoutSelectRoute: typeof StyleguideLayoutSelectRoute
  StyleguideLayoutSeparatorRoute: typeof StyleguideLayoutSeparatorRoute
  StyleguideLayoutShadowsRoute: typeof StyleguideLayoutShadowsRoute
  StyleguideLayoutSheetRoute: typeof StyleguideLayoutSheetRoute
  StyleguideLayoutSidebarRoute: typeof StyleguideLayoutSidebarRoute
  StyleguideLayoutSkeletonRoute: typeof StyleguideLayoutSkeletonRoute
  StyleguideLayoutSpacingRoute: typeof StyleguideLayoutSpacingRoute
  StyleguideLayoutTableRoute: typeof StyleguideLayoutTableRoute
  StyleguideLayoutTabsRoute: typeof StyleguideLayoutTabsRoute
  StyleguideLayoutTextareaRoute: typeof StyleguideLayoutTextareaRoute
  StyleguideLayoutToastRoute: typeof StyleguideLayoutToastRoute
  StyleguideLayoutTypographyRoute: typeof StyleguideLayoutTypographyRoute
  StyleguideLayoutIndexRoute: typeof StyleguideLayoutIndexRoute
}

const StyleguideLayoutRouteChildren: StyleguideLayoutRouteChildren = {
  StyleguideLayoutAlertsRoute: StyleguideLayoutAlertsRoute,
  StyleguideLayoutAvatarRoute: StyleguideLayoutAvatarRoute,
  StyleguideLayoutBadgesRoute: StyleguideLayoutBadgesRoute,
  StyleguideLayoutBreadcrumbRoute: StyleguideLayoutBreadcrumbRoute,
  StyleguideLayoutButtonsRoute: StyleguideLayoutButtonsRoute,
  StyleguideLayoutCalendarRoute: StyleguideLayoutCalendarRoute,
  StyleguideLayoutCardsRoute: StyleguideLayoutCardsRoute,
  StyleguideLayoutColorsRoute: StyleguideLayoutColorsRoute,
  StyleguideLayoutCommandRoute: StyleguideLayoutCommandRoute,
  StyleguideLayoutDatePickerRoute: StyleguideLayoutDatePickerRoute,
  StyleguideLayoutDialogRoute: StyleguideLayoutDialogRoute,
  StyleguideLayoutDropdownMenuRoute: StyleguideLayoutDropdownMenuRoute,
  StyleguideLayoutFormsRoute: StyleguideLayoutFormsRoute,
  StyleguideLayoutInputRoute: StyleguideLayoutInputRoute,
  StyleguideLayoutPopoverRoute: StyleguideLayoutPopoverRoute,
  StyleguideLayoutSelectRoute: StyleguideLayoutSelectRoute,
  StyleguideLayoutSeparatorRoute: StyleguideLayoutSeparatorRoute,
  StyleguideLayoutShadowsRoute: StyleguideLayoutShadowsRoute,
  StyleguideLayoutSheetRoute: StyleguideLayoutSheetRoute,
  StyleguideLayoutSidebarRoute: StyleguideLayoutSidebarRoute,
  StyleguideLayoutSkeletonRoute: StyleguideLayoutSkeletonRoute,
  StyleguideLayoutSpacingRoute: StyleguideLayoutSpacingRoute,
  StyleguideLayoutTableRoute: StyleguideLayoutTableRoute,
  StyleguideLayoutTabsRoute: StyleguideLayoutTabsRoute,
  StyleguideLayoutTextareaRoute: StyleguideLayoutTextareaRoute,
  StyleguideLayoutToastRoute: StyleguideLayoutToastRoute,
  StyleguideLayoutTypographyRoute: StyleguideLayoutTypographyRoute,
  StyleguideLayoutIndexRoute: StyleguideLayoutIndexRoute,
}

const StyleguideLayoutRouteWithChildren =
  StyleguideLayoutRoute._addFileChildren(StyleguideLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StyleguideLayoutRoute: StyleguideLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
